
-- 4. Add entity class SessionInfo and add below public properties.
USE EventDb

CREATE TABLE SESSIONINFO (
SESSION_ID INT PRIMARY KEY,
EVENT_ID INT NOT NULL,
SESSION_TITLE VARCHAR(50) NOT NULL
	CHECK (LEN(SESSION_TITLE) BETWEEN 1 AND 50),
SPEAKERID INT NOT NULL,
DESCRIPTION VARCHAR(250) NULL,
SESSION_START DATETIME NOT NULL,
SESSION_END DATETIME NOT NULL,
SESSION_URL VARCHAR(250),

FOREIGN KEY(EVENT_ID) REFERENCES EVENTDETAILS(EVENT_ID),
FOREIGN KEY (SPEAKERID) REFERENCES SPEAKERDETAILS(SPEAKERID)

);

SELECT * FROM SESSIONINFO;