-- 2. Event Details

USE EventDb

CREATE TABLE EVENTDETAILS(
EVENT_ID INT PRIMARY KEY,
EVENT_NAME VARCHAR(50) NOT NULL
CHECK (LEN(EVENT_NAME) BETWEEN 1 AND 50),
EVENT_CATEGORY VARCHAR(50) NOT NULL
CHECK (LEN(EVENT_CATEGORY) BETWEEN 1 AND 50),
EVENTDATE DATETIME NOT NULL,
DESCRIPTION VARCHAR(200) NULL,
STATUS VARCHAR(20)
CHECK (STATUS IN ('ACTIVE','INACTIVE'))
);

SELECT * FROM EVENTDETAILS;