
--6. Add entity class ParticipantEventDetails and add below public properties.

USE EventDb;


CREATE TABLE ParticipantEventDetails(
ID INT PRIMARY KEY,
ParticipantEmailId VARCHAR(100) NOT NULL,
EVENT_ID INT NOT NULL,
SESSION_ID INT NOT NULL,
ISATTENDED BIT CHECK(ISATTENDED IN (0,1)),

FOREIGN KEY(ParticipantEmailId) REFERENCES USERINFO1(EMAILID),
FOREIGN KEY(EVENT_ID) REFERENCES EVENTDETAILS(EVENT_ID),
FOREIGN KEY(SESSION_ID) REFERENCES SESSIONINFO(SESSION_ID)
);

SELECT * FROM ParticipantEventDetails;
