
SELECT name FROM sys.databases;

USE EventDb;

CREATE TABLE USERINFO1 (
    EMAILID VARCHAR(100) PRIMARY KEY,
    USERNAME VARCHAR(50) NOT NULL
	CHECK (LEN(USERNAME) BETWEEN 1 AND 50),
	ROLE VARCHAR(20) NOT NULL
	CHECK(ROLE IN ('Admin','Participant')),
	PASSWORD VARCHAR(20) NOT NULL
	CHECK (LEN(PASSWORD) BETWEEN 6 AND 20)
);

SELECT * FROM USERINFO1;

INSERT INTO USERINFO1 VALUES('JAYA@GMAIL.COM', 'JAYA', 'ADMIN', 'JAYA@2004');



