
--3. SPEAKERDETAILS

USE EventDb

CREATE TABLE SPEAKERDETAILS (
    SPEAKERID INT PRIMARY KEY,
    SPEAKER_NAME VARCHAR(50) NOT NULL
        CHECK (LEN(SPEAKER_NAME) BETWEEN 1 AND 50)
);

SELECT * FROM SPEAKERDETAILS;